# Generated by Django 3.2.4 on 2021-07-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=400, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=400, verbose_name='Nazwisko')),
                ('telefon', phone_field.models.PhoneField(blank=True, help_text='Numer telefonu', max_length=31)),
                ('typ', models.IntegerField(choices=[(1, 'Początkujący (Zielony)'), (2, 'Średnio zaawansowany (Niebieski)'), (3, 'Zaawansowany (Czerwony)')], verbose_name='Rodzaj kuriera')),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurier',
                'verbose_name_plural': 'Kurierzy',
            },
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=400, verbose_name='Nazwa')),
                ('data_dodania', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Rower',
                'verbose_name_plural': 'Rowery',
            },
        ),
        migrations.CreateModel(
            name='UzycieRoweru',
            fields=[
                ('rower', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kurier_rest.rower', verbose_name='Historia użytkowania rowerów')),
                ('data_od', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data od')),
                ('data_do', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do')),
            ],
        ),
        migrations.CreateModel(
            name='Zmiana',
            fields=[
                ('kurier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kurier_rest.kurier', verbose_name='Kurier')),
                ('data_od', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data od')),
                ('data_do', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do')),
                ('uzycie_roweru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowery', to='kurier_rest.uzycieroweru', verbose_name='Historia użytkowania rowerów')),
            ],
        ),
    ]
