# Generated by Django 3.2.4 on 2021-07-10 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=400, verbose_name='Nazwa')),
                ('data_dodania', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Rower',
                'verbose_name_plural': 'Rowery',
            },
        ),
    ]
