# Generated by Django 3.2.4 on 2021-07-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zmiana',
            name='uzycie_roweru',
        ),
        migrations.AddField(
            model_name='uzycieroweru',
            name='zmiana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowery', to='kurier_rest.zmiana', verbose_name='Historia użytkowania rowerów'),
        ),
    ]
