# Generated by Django 3.2.4 on 2021-07-11 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('38d0df3f-ab96-4453-8557-57f1de9cf510'), editable=False, primary_key=True, serialize=False),
        ),
    ]
