# Generated by Django 3.2.4 on 2021-07-11 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0002_rower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
