# Generated by Django 3.2.4 on 2021-07-11 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0002_alter_rower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('af6aedf9-3575-4db0-b1c7-9f89ed5d2ef0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
