# Generated by Django 3.2.4 on 2021-07-11 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0003_alter_rower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('1f236373-0db6-42a2-bf84-bd5cccef34a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
