# Generated by Django 3.2.4 on 2021-07-11 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0003_alter_rower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4702414a-d8ce-4532-b9ab-29c98779f6fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
