# Generated by Django 3.2.4 on 2021-07-11 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0004_alter_rower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2441e77e-f159-47e3-a555-54e14aa5f97c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
