# Generated by Django 3.2.4 on 2021-07-11 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0005_alter_rower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7be131f2-712e-42c8-b896-332b83d81de2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
