# Generated by Django 3.2.4 on 2021-07-11 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_rest', '0007_auto_20210711_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('a1565759-595a-4117-8c76-bfad098235a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
